[2025-07-31T00:58:54.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T00:58:54.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_wcccccccck.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T00:58:54.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_wcccccccck.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [queued]>
[2025-07-31T00:58:54.835+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T00:58:54.850+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_task> on 2025-06-25 00:00:00+00:00
[2025-07-31T00:58:54.861+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3333) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-31T00:58:54.862+0000] {standard_task_runner.py:63} INFO - Started process 3335 to run task
[2025-07-31T00:58:54.861+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_wcccccccck', 'extract_data_task', 'scheduled__2025-06-25T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator_python.py', '--cfg-path', '/tmp/tmp77rrgjxa']
[2025-07-31T00:58:54.863+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask extract_data_task
[2025-07-31T00:58:54.917+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_wcccccccck.extract_data_task scheduled__2025-06-25T00:00:00+00:00 [running]> on host 14614e29d246
[2025-07-31T00:58:55.007+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_wcccccccck' AIRFLOW_CTX_TASK_ID='extract_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-25T00:00:00+00:00'
[2025-07-31T00:58:55.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T00:58:55.021+0000] {__init__.py:56} INFO - 執行 extract_data (資料載入層)
[2025-07-31T00:58:55.022+0000] {__init__.py:60} INFO - 呼叫演算法 'test_csv' 來自模組 'processor.extract.readNP'
[2025-07-31T00:58:55.022+0000] {logging_mixin.py:188} INFO - test.npy
[2025-07-31T00:58:55.025+0000] {__init__.py:75} ERROR - extract_data 發生例外: 'numpy.ndarray' object has no attribute 'to_parquet'
[2025-07-31T00:58:55.025+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T00:58:55.025+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/processor/__init__.py", line 65, in extract_data
    data.to_parquet(buf, index=False)
    ^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'to_parquet'
[2025-07-31T00:58:55.036+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_wcccccccck, task_id=extract_data_task, run_id=scheduled__2025-06-25T00:00:00+00:00, execution_date=20250625T000000, start_date=20250731T005854, end_date=20250731T005855
[2025-07-31T00:58:55.049+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task extract_data_task ('numpy.ndarray' object has no attribute 'to_parquet'; 3335)
[2025-07-31T00:58:55.075+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T00:58:55.101+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T00:58:55.107+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
